using System.Collections.Generic;
using NeptuneEvo.BattlePass.Models;
using NeptuneEvo.Chars.Models;

namespace NeptuneEvo.BattlePass.Season1Models
{
    public static class Repository
    {
               
        public static readonly List<BattlePassTask> BattlePassTask = new List<BattlePassTask>
        {
	        new BattlePassTask(0, "Gun Game teilnehmen!", 1, 30, "Lass uns gehen", "Ungewöhnliche Aufgabe", 777, BattlePassRewardDiff.Medium),
			new BattlePassTask(1, "Kaufen Sie eine Waffenmodifikation im Ammunition", 1, 30, "Waffenanpassung", "Leichte Aufgabe", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(2, "Fahren Sie 5 Meilen mit einem Fahrgast als Taxifahrer", 5, 30, "Taxifahrer", "Ungewöhnliche Aufgabe", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(3, "Spielen Sie Minensucher (F9)", 1, 30, "Bomb has been defused", "Ungewöhnliche Aufgabe", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(4, "Spielen Sie an den Glücksspielautomaten im Casino", 1, 30, "7-7-7", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(5, "Zahlen Sie 10$ auf Ihr Bankkonto ein", 1, 30, "Money Money", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(6, "Einen Lotto Schein in 24/7 kaufen", 1, 30, "Glückspilz?", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(7, "Einen Spieler mit einem Verbandskasten reanimieren", 1, 30, "I need a medic!", "Schwierige Aufgabe", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(8, "Kaufen Sie eine beliebige Kleidung im Kleidungsladen", 1, 30, "Stilvoll", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(9, "Starte einen Staatlichen Job", 1, 30, "Schon wieder arbeiten ...", "Leichte Aufgabe", 420, BattlePassRewardDiff.Easy),
			new BattlePassTask(10, "Kündige deinen Job", 1, 30, "Wochenende!", "Leichte Aufgabe", 333, BattlePassRewardDiff.Easy),
			new BattlePassTask(11, "Schalten Sie 3 Anzeigen in NEWS über das Telefon", 3, 30, "Jeder soll mich höhren", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(12, "Repariere das Fahrzeug mit einem Schraubenschlüssel", 1, 30, "Schraubenschlüssel", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(13, "Repariere ein Fahrzeug beim Mechaniker an der Markierung", 1, 30, "Repariere mein Fahrzeug!", "Ungewöhnliche Aufgabe", 250, BattlePassRewardDiff.Medium),
			new BattlePassTask(14, "Jemanden Geld übergeben", 1, 30, "Gib geld Bruder", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(15, "Eine Tablette von einem Arzt kaufen", 1, 30, "Doktor", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(16, "Werfe einen beliebigen Gegenstand auf den Boden", 1, 30, "Verstecke es", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(17, "Einen beliebigen Gegenstand vom Boden aufheben", 1, 30, "Verwechselt", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(18, "Eine Tätowierung an einem beliebigen Körperteil machen lassen", 1, 30, "Tätowierer, stich mich", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(19, "20 Liter Kraftstoff an einer Tankstelle tanken", 1, 30, "Tanken", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(20, "10 Pakete als Postbote ausliefern", 9, 30, "Post ist da", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(21, "Als Gärtner 20 Markierungen durchfahren", 20, 30, "Illegaler Rennfahrer", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(22, "20 Spulen als Elektriker reparieren", 20, 30, "Warum liegt hier Stroh?", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			//new BattlePassTask(23, "Ein Feuerwerk zünden", 1, 30, "Silvester", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(24, "Als Mechaniker zu einem Einsatz kommen", 1, 30, "Gaspedal durchdrücken", "Ungewöhnliche Aufgabe", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(25, "Ein Haus (außer das Eigene) betreten", 1, 30, "Besucher", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(26, "Ein Fahrzeug mieten", 1, 30, "Carsharing", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(27, "Fahrzeug waschen", 1, 30, "Waschanlage", "Leichte Aufgabe", 666, BattlePassRewardDiff.Easy),
			//new BattlePassTask(28, "Ein beliebiges Feuerwerk kaufen", 1, 30, "Geld wegwerfen", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(29, "Bier bei 24/7 kaufen", 1, 30, "Helles ungefiltertes Bier...", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(30, "Paar-Animation benutzen", 1, 30, "Interaktion ist alles", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(31, "Etwas im RP-Chat schreiben (/me)", 1, 30, "Roleplay", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(32, "Drei Spielern die Hand schütteln", 3, 30, "Kennenlernen", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(33, "Eine Probefahrt machen", 1, 30, "Angeben", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(34, "Eine beliebige Maske im Maskenladen kaufen", 1, 30, "Maskenmann", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(35, "An einem Straßenrennen teilnehmen", 1, 30, "Fast & Furious", "Schwierige Aufgabe", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(36, "Eine Liebesbotschaft im Handel verschenken", 1, 30, "Aufmerksamkeit", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(37, "Bier im Handel weitergeben", 1, 30, "Teile dein Bier mit deinem nächsten!", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(38, "Ein Baumarkt besuchen", 1, 30, "Am Rande", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(39, "Nutze einen beliebigen Geldautomaten", 1, 30, "Passwort eingeben", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(40, "Tanken Sie an einer Tankstelle auf", 1, 30, "Voll Tank!", "Leichte Aufgabe", 350, BattlePassRewardDiff.Easy),
			new BattlePassTask(41, "Übergebe jemandem einen Revolver", 1, 30, "Cowboy", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(42, "Tanken Sie Ihr Fahrzeug aus einem Kanister", 1, 30, "Tank es auf!", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(43, "Kaufen Sie Informationen über ein Haus bei einer Immobilienagentur", 1, 30, "Schnäppchenjäger", "Schwierige Aufgabe", 2228, BattlePassRewardDiff.Hard),
			new BattlePassTask(44, "Kaufen Sie etwas bei LS Customs", 1, 30, "Tuning", "Schwierige Aufgabe", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(45, "Kaufen Sie einen Schlüsselbund bei 24/7", 1, 30, "Schlüsselbund", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(46, "Parke ein Fahrzeug in deine Garage", 1, 30, "Selbstrettungsexperte", "Schwierige Aufgabe", 444, BattlePassRewardDiff.Hard),
			new BattlePassTask(47, "Miete ein Zelt am Markt", 1, 30, "Verkäufer", "Schwierige Aufgabe", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(48, "Etwas auf dem Markt kaufen", 1, 30, "Käufer", "Schwierige Aufgabe", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(49, "Verlängere die Zeltmiete auf dem Markt", 1, 30, "Businessman", "Schwierige Aufgabe", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(50, "Öffne eine beliebige Lootbox", 1, 30, "Versuche dein Glück", "Schwierige Aufgabe", 250, BattlePassRewardDiff.Hard),
			new BattlePassTask(51, "Rufe einen Staatsbeamten mit Hilfe eines NPCs", 1, 30, "Ich brauche Hilfe!", "Schwierige Aufgabe", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(52, "Handel eine Pizza per Handel weiter", 1, 30, "Teile eine Pizza mit deinen Nachbarn!", "Ungewöhnliche Aufgabe", 444, BattlePassRewardDiff.Medium),
			new BattlePassTask(53, "Kauf dir etwas beim Barber Shop", 1, 30, "Hallo, schneide meine Haare", "Ungewöhnliche Aufgabe", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(54, "Jemanden Drogen geben", 1, 30, "Dealer", "Schwierige Aufgabe", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(55, "Spiele im Casino", 1, 30, "Alles verloren!", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(56, "Wiederhole die Animation einer anderen Person über das G-Menü", 1, 30, "Repeat", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(57, "Etwas im Baumarkt kaufen", 1, 30, "Abgelegenes Geschäft...", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(58, "Repariere 3 Fahrzeuge als Mechaniker", 3, 30, "Leitender Mechaniker", "Schwierige Aufgabe", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(59, "Fahren Sie 15 Meilen mit einem Fahrgast als Taxifahrer", 15, 30, "Kenne die Straße", "Schwierige Aufgabe", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(60, "PayDay erhalten", 1, 30, "Gehaltseingang!", "Leichte Aufgabe", 420, BattlePassRewardDiff.Easy),
			new BattlePassTask(61, "Chips essen", 1, 30, "Lecker, Chips..", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(62, "Bestelle ein Taxi 2mal", 2, 30, "TAXIIIII!", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(63, "Kauf dir ein Ticket und fahre als Fahrgast mit dem Bus", 1, 30, "Ticket bitte!", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(64, "20 Markierungen als Busfahrer fahren", 20, 30, "Upps, falscher Weg", "Schwierige Aufgabe", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(65, "Einen Mechaniker rufen", 1, 30, "Reparieren!", "Leichte Aufgabe", 777, BattlePassRewardDiff.Easy),
			new BattlePassTask(66, "Ein Bier trinken", 1, 30, "Nicht 'Bier' sondern 'Pivo'", "Leichte Aufgabe", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(67, "Rauche eine Wasserpfeife 3mal", 3, 30, "Chillen", "Schwierige Aufgabe", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(68, "Führe 5 Vapezügige durch", 5, 30, "Dampfen", "Ungewöhnliche Aufgabe", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(69, "Rauche eine Bong", 1, 30, "Es ist 4:20 Uhr ...", "Ungewöhnliche Aufgabe", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(70, "Verwende eine beliebige Animation 3 mal", 3, 30, "Tanzshow", "Leichte Aufgabe", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(71, "Einmal an einer Vape ziehen", 1, 30, "Dampfen", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(72, "Handel mit einem anderen Spieler", 1, 30, "Handel", "Ungewöhnliche Aufgabe", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(73, "Lege einen Schlüssel ins Schlüsselbund", 1, 30, "Hast du mehr als zwei Fahrzeuge?", "Schwierige Aufgabe", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(74, "Funkgerät verwenden", 1, 30, "Pshshsh... kannst du mich hören?", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(75, "Verschenke eine Rose durch Handeln", 1, 30, "Valentinstag", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(76, "Telefonnummer in Kontakte aufnehmen", 1, 30, "WhatsUp?", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(77, "Schreibe 3 SMS an jemanden, der 'online' ist", 3, 30, "Kommunikation ist der Schlüssel zum Erfolg", "Schwierige Aufgabe", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(78, "Bearbeite einen vorhandenen Kontakt im Telefon", 1, 30, "Hallo, was geht?", "Schwierige Aufgabe", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(79, "Spiele etwas in /do", 1, 30, "Perspektivwechsel", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(80, "Flüstere etwas /w", 1, 30, "Ich flüstere dir ins Ohr", "Ungewöhnliche Aufgabe", 250, BattlePassRewardDiff.Medium),
			new BattlePassTask(81, "Schreie etwas /s", 1, 30, "Lass es krachen", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(82, "Mach etwas in /try", 1, 30, "Kopf oder Zahl", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(83, "Parke deine Fahrzeuge in der Garage mit der Funktion Parken um", 1, 30, "Perfektionist", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(84, "Sprich mit einem NPC im Polizeirevier", 1, 30, "This is the police", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(85, "Sprich mit einem NPC im Krankenhaus", 1, 30, "Medizinische Ratschläge", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(86, "Schnalle den Sicherheitsgurt an", 1, 30, "Oh, das tut weh", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(87, "Motorhaube eines Fahrzeugs öffnen", 1, 30, "Mechaniker", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(88, "Klettere in den Kofferraum eines Fahrzeugs", 1, 30, "In den Wald", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(89, "Zeige dreimal mit dem Finger", 3, 30, "Wo?", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(90, "Lege einen Gegenstand in den Kofferraum", 1, 30, "Mobiles Lager", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(91, "Repariere ein Fahrzeug als Mechaniker", 1, 30, "Mechaniker", "Schwierige Aufgabe", 444, BattlePassRewardDiff.Hard),
			new BattlePassTask(92, "Liefere 10 Geldsäcke als Geldtransporteur aus", 10, 30, "Money Money Money", "Schwierige Aufgabe", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(93, "Schreibe eine Nachricht auf der Straße (/aktion)", 1, 30, "Werbegestalter 66", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(94, "Benutze ein Verbandskasten", 1, 30, "Verbandskasten", "Ungewöhnliche Aufgabe", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(95, "Fahre 10 Meilen als Passagier eines Taxis", 10, 30, "Fahr weiter!", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(96, "Erhalte ein Duplikat des Schlüssels für das Fahrzeug", 1, 30, "Schlosswechsel", "Schwierige Aufgabe", 555, BattlePassRewardDiff.Hard),
			new BattlePassTask(97, "Sprich mit einem Quest-Charakter", 1, 30, "Plauderer", "Schwierige Aufgabe", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(98, "Beginne eine Behandlung im Krankenhaus", 1, 30, "Bitte, helft mir!", "Schwierige Aufgabe", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(99, "Benutze ein Objekt mit dem Schnellzugriff", 1, 30, "So einfach gehts!", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(100, "Etwas in /todo erledigen", 1, 30, "Roleplayer", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(101, "Jemandem deinen Pass zeigen", 1, 30, "Papiere, bitte", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(102, "Im Casino würfeln (/dice)", 1, 30, "Süchtig", "Schwierige Aufgabe", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(103, "Brechstange bei 24/7 kaufen", 1, 30, "Einbrecher", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(104, "Taschenlampe bei 24/7 kaufen", 1, 30, "Bei Nacht...", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(105, "Schraubenschlüssel bei 24/7 kaufen", 1, 30, "Ich laufe, Vater!", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(106, "Hammer bei 24/7 kaufen", 1, 30, "Zimmermann", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(107, "Chips bei 24/7 kaufen", 1, 30, "Hmmm Chips", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(108, "Pizza bei 24/7 kaufen", 1, 30, "Ich habe Hunger!", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(109, "Kanister bei 24/7 kaufen", 1, 30, "Braucht jeder Autofahrer", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(110, "Liebesbrief bei 24/7 kaufen", 1, 30, "Zeit für Liebe", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(111, "Fernglas bei 24/7 kaufen", 1, 30, "Beobachten", "Leichte Aufgabe", 2222, BattlePassRewardDiff.Easy),
			new BattlePassTask(112, "Vape bei 24/7 kaufen", 1, 30, "Vape Nation", "Leichte Aufgabe", 777, BattlePassRewardDiff.Easy),
			new BattlePassTask(113, "Regenschirm bei 24/7 kaufen", 1, 30, "Regnet es?", "Leichte Aufgabe", 555, BattlePassRewardDiff.Easy),
			new BattlePassTask(114, "Gitarre bei 24/7 kaufen", 1, 30, "Rockstar", "Leichte Aufgabe", 1111, BattlePassRewardDiff.Easy),
			new BattlePassTask(115, "Kamera bei 24/7 kaufen", 1, 30, "Influencer?", "Leichte Aufgabe", 1500, BattlePassRewardDiff.Easy),
			new BattlePassTask(116, "Mikrofon bei 24/7 kaufen", 1, 30, "Superstar", "Leichte Aufgabe", 1111, BattlePassRewardDiff.Easy),
			new BattlePassTask(117, "Ball bei 24/7 kaufen", 1, 30, "Baseball", "Leichte Aufgabe", 444, BattlePassRewardDiff.Easy),
			new BattlePassTask(118, "Burger bei Burgerladen kaufen", 1, 30, "Big Smoke bestellung", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(119, "Hot-Dog bei Burgerladen kaufen", 1, 30, "Hot-Dog", "Leichte Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(120, "Werfe 'Geschickt' mit /try weg", 1, 30, "Glück ist auf deiner Seite", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(121, "Sprunk bei Burgerladen kaufen", 1, 30, "Fast wie Sprite...", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(122, "Gib jemandem einen Hotdog", 1, 30, "Teile eine Wurst mit dem Nächsten!", "Ungewöhnliche Aufgabe", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(123, "Verschenke jemanden eine kostenlose Case", 1, 30, "Geschenke sind wichtig", "Schwierige Aufgabe", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(124, "Öffne dein Haus", 1, 30, "Gäste empfangen", "Schwierige Aufgabe", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(125, "Schließe dein Haus", 1, 30, "Ich erwarte keine Gäste", "Schwierige Aufgabe", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(126, "Als Beifahrer jemanden den Weg zeigen", 1, 30, "Fahr mich bitte dahin!", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(127, "Sandwich bei Burgerladen kaufen", 1, 30, "Subway", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(128, "eCola bei Burgerladen kaufen", 1, 30, "Gib mir Colaaa", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(129, "Besuche und erkunde einen beliebigen Waffenladen", 1, 30, "Brauche ich einen Waffenschein?", "Leichte Aufgabe", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(130, "Kaufe eine beliebige Waffe im Waffenladen", 1, 30, "Selbstschutz", "Ungewöhnliche Aufgabe", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(131, "Spiele Mafia", 1, 30, "In diesem Land musst du zuerst Geld machen!", "Schwierige Aufgabe", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(132, "Spiele Tank Royale", 1, 30, "Grüße an die Panzerbesatzungen", "Ungewöhnliche Aufgabe", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(133, "Jemandem einen Schraubenschlüssel zur Reparatur des Fahrzeugs übergeben", 1, 30, "Schlüssel von meinem Herzen...", "Ungewöhnliche Aufgabe", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(134, "Pizza essen", 1, 30, "Fastfood", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(135, "Sandwich essen", 1, 30, "Subway", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(136, "Sprunk trinken", 1, 30, "Erfrischung", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(137, "Hot-Dog essen", 1, 30, "Hot-Dog", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(138, "eCola trinken", 1, 30, "Cola", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(139, "Einen Joint rauchen", 1, 30, "Entspannen", "Ungewöhnliche Aufgabe", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(140, "Burger essen", 1, 30, "Burger Burger", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(141, "e-Cola Handeln", 1, 30, "Teile es mit jemanden", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(142, "Sprunk Handeln", 1, 30, "Teile es mit jemanden", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(143, "Burger Handeln", 1, 30, "Teile es mit jemanden", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(144, "Sandwich Handeln", 1, 30, "Teile es mit jemanden", "Leichte Aufgabe", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(145, "Verbandskasten Handeln", 1, 30, "Heile Dich, Bruder", "Ungewöhnliche Aufgabe", 222, BattlePassRewardDiff.Medium),
			new BattlePassTask(146, "Notiz Handeln", 1, 30, "Nachricht", "Schwierige Aufgabe", 222, BattlePassRewardDiff.Hard),
			
        };

		public static List<BattlePassReward> BattlePassAwards = new List<BattlePassReward>
		{
			new BattlePassReward(0, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(1, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(2, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
			new BattlePassReward(3, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Rose, count: 1),
			new BattlePassReward(7, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(8, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(9, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pistol, count: 1),
			new BattlePassReward(11, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(12, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.Umbrella, count: 1),
			new BattlePassReward(14, type: BattlePassRewardType.Item, itemId: (int)ItemId.AssaultRifleMk2, count: 1),
			new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(16, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(18, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(19, type: BattlePassRewardType.Vip, itemId: 4, count: 2),
			new BattlePassReward(20, type: BattlePassRewardType.Item, itemId: (int)ItemId.Vape, count: 1, data:"100"),
			new BattlePassReward(21, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(22, type: BattlePassRewardType.Money, count: 777),
			//new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.Revolver, count: 1),
			new BattlePassReward(24, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework3, count: 3),
			new BattlePassReward(26, type: BattlePassRewardType.Money, count: 666),
			new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			//new BattlePassReward(28, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(29, type: BattlePassRewardType.Money, count: 888),
			new BattlePassReward(30, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(31, type: BattlePassRewardType.Item, itemId: (int)ItemId.Gusenberg, count: 1),
			new BattlePassReward(32, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(34, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework1, count: 3),
			new BattlePassReward(36, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pickaxe1, count: 1, data:"300"),
			new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.LoveNote, count: 1),
			new BattlePassReward(38, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(39, type: BattlePassRewardType.Donate, count: 111),
			new BattlePassReward(40, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(41, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(42, type: BattlePassRewardType.Item, itemId: (int)ItemId.Microphone, count: 1),
			new BattlePassReward(43, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(45, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework3, count: 3),
			new BattlePassReward(46, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(47, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(48, type: BattlePassRewardType.Item, itemId: (int)ItemId.SMG, count: 1),
			new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(50, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(51, type: BattlePassRewardType.Item, itemId: (int)ItemId.Revolver, count: 1),
			new BattlePassReward(52, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
			new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(54, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(55, type: BattlePassRewardType.Item, itemId: (int)ItemId.Rose, count: 1),
			new BattlePassReward(56, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(57, type: BattlePassRewardType.Item, itemId: (int)ItemId.Musket, count: 1),
			new BattlePassReward(58, type: BattlePassRewardType.Donate, count: 111),
			new BattlePassReward(59, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pistol, count: 1),
			new BattlePassReward(61, type: BattlePassRewardType.Item, itemId: (int)ItemId.WorkAxe, count: 1, data:"1250"),
			new BattlePassReward(62, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(63, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(63, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework3, count: 3),
			new BattlePassReward(65, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(66, type: BattlePassRewardType.Donate, count: 111),
			new BattlePassReward(67, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(68, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(69, type: BattlePassRewardType.Item, itemId: (int)ItemId.AssaultShotgun, count: 1),
			new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Guitar, count: 1),
			new BattlePassReward(71, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(72, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(73, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(73, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(75, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(76, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(78, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(79, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(81, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(83, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(84, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework2, count: 3),
			new BattlePassReward(86, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pickaxe2, count: 1, data:"1248"),
			new BattlePassReward(87, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(88, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(89, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(90, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.SMGMk2, count: 1),
			new BattlePassReward(92, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(93, type: BattlePassRewardType.Money, count: 1228),
			new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(95, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(96, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(97, type: BattlePassRewardType.Money, count: 1228),
			new BattlePassReward(98, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(99, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.SNSPistol, count: 1),
			new BattlePassReward(101, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(102, type: BattlePassRewardType.Money, count: 1337),
			new BattlePassReward(103, type: BattlePassRewardType.Item, itemId: (int)ItemId.VintagePistol, count: 1),
			new BattlePassReward(104, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(107, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(108, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(109, type: BattlePassRewardType.Money, count: 1337),
			new BattlePassReward(110, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Camera, count: 1),
			new BattlePassReward(112, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(113, type: BattlePassRewardType.Item, itemId: (int)ItemId.Bong, count: 1, data:"420"),
			new BattlePassReward(114, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(115, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(116, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pickaxe3, count: 1, data: "2250"),
			new BattlePassReward(117, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(118, type: BattlePassRewardType.Money, count: 1337),
			new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.Hookah, count: 1, data:"1000"),
			new BattlePassReward(120, type: BattlePassRewardType.Donate, count: 200),
			new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(123, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(124, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
			new BattlePassReward(125, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
			new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
			new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(128, type: BattlePassRewardType.Donate, count: 420),
			new BattlePassReward(129, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
			new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
			new BattlePassReward(131, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"Niva", name:"Niva", count: 1),
		};

		public static List<BattlePassReward> BattlePassAwardsPremium = new List<BattlePassReward>
		{
			new BattlePassReward(0, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(1, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(1, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(2, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(3, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(3, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_0_False", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_0_False", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_0_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(7, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(7, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(8, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(9, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(9, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(11, type: BattlePassRewardType.Item, itemId: (int)ItemId.CombatMGMk2, count: 1),
            new BattlePassReward(12, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "163_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(12, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "173_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_0_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(14, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(16, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(18, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
            new BattlePassReward(19, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "462_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(19, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "485_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(20, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_1_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_1_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(22, type: BattlePassRewardType.Item, itemId: (int)ItemId.FlareGun, count: 1),
            new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_0_True", gender: BattlePassRewardGender.Man),
            //new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "163_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "173_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(26, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_1_False", gender: BattlePassRewardGender.Woman),
            //new BattlePassReward(28, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_1_True", gender: BattlePassRewardGender.Man),
            //new BattlePassReward(28, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(29, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(30, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_2_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(30, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_2_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(31, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(31, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(32, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(32, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_2_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_2_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(34, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "462_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "485_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(36, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_1_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_1_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(38, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(38, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(39, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(39, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(40, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(41, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(41, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_0_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(42, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(43, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(43, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(45, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(46, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_3_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(46, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_3_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(47, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
            new BattlePassReward(48, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(48, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_3_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_3_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(50, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(51, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(51, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(52, type: BattlePassRewardType.Money, count: 5000),
            new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_1_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_1_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(54, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(54, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(55, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
            new BattlePassReward(56, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(56, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(57, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(58, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_4_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(58, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_4_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(59, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(61, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(61, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(62, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_5_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(62, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_5_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(63, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavyShotgun, count: 1),
            new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(65, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(66, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_4_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(66, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_4_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(67, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(68, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(68, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(69, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_6_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_6_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(71, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(71, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(72, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(72, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(73, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(75, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(76, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(76, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(78, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(79, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(79, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_7_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_7_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(81, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(83, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(84, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(86, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_5_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(86, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_5_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(87, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(87, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(88, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "462_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(88, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "485_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(89, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(90, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_8_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(90, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_8_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(92, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(93, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(95, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(95, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(96, type: BattlePassRewardType.Vip, itemId: 4, count: 10),
            new BattlePassReward(97, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(97, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(98, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(98, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(99, type: BattlePassRewardType.Item, itemId: (int)ItemId.RevolverMk2, count: 1),
            new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_9_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_9_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(101, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
            new BattlePassReward(102, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(102, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(103, type: BattlePassRewardType.Item, itemId: (int)ItemId.MarksmanRifle, count: 1),
            new BattlePassReward(104, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "163_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(104, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "173_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(107, type: BattlePassRewardType.Donate, count: 250),
            new BattlePassReward(108, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(109, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(109, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(110, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(110, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(112, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_4_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(112, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_4_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(113, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(114, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_4_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(114, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_4_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(115, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(116, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
            new BattlePassReward(117, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(117, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(118, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(118, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_5_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_5_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(120, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(120, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_5_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_5_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_6_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_6_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(123, type: BattlePassRewardType.Donate, count: 333),
            new BattlePassReward(124, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
            new BattlePassReward(125, type: BattlePassRewardType.Vip, itemId: 4, count: 10),
            new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_2_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_2_True", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(129, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_7_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_7_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(131, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, count: 1, data: "lc100", name:"Land Cruiser 100"),
		};

    }
}